### ISSUE TITLE
Create payment for invoice

### ISSUE THREAD

**Issue by chris8182** [zoho/books-dotnet-wrappers#1]
Hello,
i can't create a payement for an invoice because the object PaymentInfo hasn't invoice_id. Do you have a solution or do you explain me how create a payment for an invoice ?

thanks you

**Comment by hari-thalapaneni** [comment]
Hi


Sorry for missing to describe the invoices property in the sample code.

The CustomerPayment object has the property invoices which is the type of List<Invoice>to create a payment to the multiple invoices.

The following snippet of code will describes that how to create a partial/full payment for the invoices.


    List<Invoice> invoicesToBePaid = new List<Invoice>();
    Invoice invoiceToPay = new Invoice()
    {
          invoice_id=invoiceId,
          amount_applied=1234.00,
          tax_amount_withheld=0.00,
    };
    invoicesToBePaid.Add(invoiceToPay);
    var newPaymentInfo = new CustomerPayment()
     {
          customer_id = customerId,
          date="2014-02-03",
          amount=1234,
          invoices=invoicesToBePaid,
    };
   var newCustomerPayment = customerpaymentsApi.Create(newPaymentInfo);


Fell free to contact us on further if you are faced any difficulties or issues.

Thanks&Regards,
Hari Krishna.T.

**Comment by chris8182** [comment]
Thanks you for your help :)


Je reste à votre disposition si vous avez besoin d'informations
supplémentaires.

Bien cordialement,

VivaSoft - Christian Pompier
Intégrateur Google Apps & Zoho CRM
Direction Générale
09-51-91-02-19 / 06-06-50-88-46
www.vivasoft.fr




2015-08-25 8:19 GMT+02:00 Hari Krishna <notifications@github.com>:
